---
title: "bee_cultures"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(maps)
library(ggplot2)
library(tidyverse)
library(sf)
library(viridis)
```

```{r}
# Get the Data

# Read in with tidytuesdayR package 
# Install from CRAN via: install.packages("tidytuesdayR")
# This loads the readme and all the datasets for the week of interest

# Either ISO-8601 date or year/week works!

tuesdata <- tidytuesdayR::tt_load('2022-01-11')
#tuesdata <- tidytuesdayR::tt_load(2022, week = 2)

colony <- tuesdata$colony
stressors <- tuesdata$stressor
MainStates <- map_data("state")

# Or read in the data manually

#colony <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-01-11/colony.csv')
#stressor <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-01-11/stressor.csv')

```


```{r data manipulation}

colony <- colony %>% mutate(region = tolower(colony$state))

merged_colony <- inner_join(MainStates, colony, by = "region")

```

```{r map making}
map_end_n <- merged_colony %>%  filter(months == "October-December") %>% 
  ggplot() + 
  geom_polygon(aes(x=long, y=lat, group = group, fill = colony_n/500),
                color = "white") +
  ggtitle("Number of colonies between October and December each year on the USA mainland\nData between 2015 and 2020") +
  scale_fill_viridis(option = "viridis",
                     begin = 0,
                     end = 1,
                     direction = -1,
                     na.value = "rey50") +
  facet_wrap(~year) +
  theme_map()
```

